### PR TITLE
Visual design

### PR DESCRIPTION
**Pull request by mayacakmak**
It would be great to have the live demo (demo.html on the git pages) include the style updates for discussion, so let's merge. Should not impact anything on the todo list.

### CODE REVIEW

**Comment by mayacakmak** [comment]
Tried to fix bug, should be ready to pull now.

**Comment by lrperlmu** [comment]
reviewing the code now...

**Comment by lrperlmu** [comment]
The bug fix is effective!

One suggestion -- what would you think of passing in the `is_app` flag into the constructor as `frame_data.is_app`, rather than hard-coding its value in the constructor body? 

Thinking forward, implementing this suggestion would make the existing frame classes more reusable (versatile). For example, when building a future app from this framework, we could use instances of `form_frame` in both the study and the app. (When I say "future app," I mean one based on the design work that you and Patrícia and Addie are doing. This suggestion could be implemented now, or at such a time as that app is being built.)

Aside from this suggestion, I believe visual_design is ready to merge into master.

**Comment by lrperlmu** [comment]
Note to self: merge these changes into the github pages branch once finished.

**Comment by lrperlmu** [comment]
Maya says: priority to merge into gh-pages. 

Regarding suggestion above: will look at it soon (today-ish), and work on it later.

**Comment by mayacakmak** [comment]
Quick question: As part of this change, do you mean to remove the default value `this.is_app = false;` from the Frame class constructor (and have it always be assigned in the extension class constructor from the data_frame passed)? In that case we would need to add `this.is_app = data_frame.is_app;` in all constructors and `frame.is_app = false;` in places where the constructor is called for non-app frames (since there would not be any default value). In addition, the setBackground() function would break if is_app is not assigned. Let me know what you think makes most sense?

Also noting we might want to do the same for summary.js > this.has_graphic (esp. if more frames might include graphics).

Lastly, minor point but I tend to use camel case in JS (similar to its default DOM variables):
https://www.w3schools.com/js/js_conventions.asp
..but noticed this codebase uses Python like style and I ended up doing a mix (e.g. 'is_app' vs. 'setBackground'). Feel free to clean up or let me know what to do in the future.

**Comment by lrperlmu** [comment]
Regarding style: Thanks for pointing that out. I ended up using python-like style and javadoc-esque comments since that's what I'm most familiar with, and I have almost no experience with JS coding conventions. This did create somewhat of a clash with library methods being camelcase. I prefer to keep the codebase self-consistent (so continue using python style for new identifiers), but as you say it's a minor point.

Investigating your other question now...

**Comment by lrperlmu** [comment]
Every child constructor needs documentation that `frame_data.is_app` is an expected field of the parameter. And the child constructor body needs to set `this.is_app = frame_data.is_app;`.

As for the default value for non-app frames such as `BlockerFrame`, I think the `Frame` constructor can keep the line `this.is_app = false;` to set a default value and ensure that it will never be undefined. It will get overwritten by the constructors of most extension classes since `super()` is called in the first line of the extension class constructors.

I think `this.has_graphic` is a bit different from `this.is_app` because the value of `has_graphic` is derived based on whether a graphic filename was passed in via `frame_data.graphic`.

**Comment by mayacakmak** [comment]
Okay, refactoring with is_app being part of the data frame given to the constructor is complete. Demo seems to be working well.

**Pull request merged**
